name: nyc-taxi-app  # Nombre del proyecto de la aplicaci√≥n

services:
  # üß© Servicio de Frontend (UI - Streamlit)
  ui:
    image: nyc-taxi-ui-image:latest                # Nombre y etiqueta de la imagen
    container_name: nyc-taxi-ui-container          # Nombre asignado al contenedor
    build:
      context: ./app/ui                            # Carpeta donde est√° el c√≥digo del frontend
      dockerfile: Dockerfile                       # Nombre del Dockerfile dentro del contexto
    ports:
      - "8501:8501"                                # Puerto UI ‚Üí http://localhost:8501
    network_mode: host                             # Usa la red del host (localhost)
    command: streamlit run main.py --server.port=8501 --server.address=0.0.0.0

  # üß† Servicio de Backend (API - FastAPI)
  api:
    image: nyc-taxi-api-image:latest               # Nombre y etiqueta de la imagen
    container_name: nyc-taxi-api-container         # Nombre asignado al contenedor
    build:
      context: ./app/api                           # Carpeta donde est√° el c√≥digo de la API
      dockerfile: Dockerfile                       # Nombre del Dockerfile dentro del contexto
    ports:
      - "8000:8000"                                # Puerto API ‚Üí http://localhost:8000
    env_file:
      - ./.env                                     # Carga variables desde el archivo .env en la ra√≠z
    network_mode: host                             # Usa la red del host (localhost)
    command: uvicorn api:app --host 0.0.0.0 --port 8000